apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-a-production
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: ./basic/service-a
    repoURL: https://github.com/trc-sdlc-huawei/gitops.git
    targetRevision: HEAD
  destination:
    name: production
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
